import { Annotation, messagesStateReducer } from "@langchain/langgraph";
import { BaseMessage } from "@langchain/core/messages";
import { RouterOutput } from './router-output.schema';

/**
 * Annotation for defining the StateGraph schema.
 */
export const AgentState = Annotation.Root({
  /**
   * The current conversation history.
   * Reducer ensures new messages are successfully appended.
   */
  messages: Annotation<BaseMessage[]>({
    reducer: messagesStateReducer,
    default: () => [],
  }),
  
  /**
   * Main context identifiers
   */
  conversationId: Annotation<string>(),
  userId: Annotation<string>(),
  
  /**
   * Router output for hint/fast-track
   */
  routerResult: Annotation<RouterOutput | null>({
    reducer: (left: RouterOutput | null, right: RouterOutput | null) => right,
    default: () => null,
  }),

  /**
   * Phase 2: Retrieved documents (for Ask/RAG)
   */
  retrievedDocs: Annotation<any[] | null>({
    reducer: (left: any[] | null, right: any[] | null) => right,
    default: () => null,
  }),

  /**
   * Phase 2: Critic evaluation result
   */
  criticResult: Annotation<any | null>({
    reducer: (left: any | null, right: any | null) => right,
    default: () => null,
  }),

  /**
   * Phase 2: CRAG relevance judgment
   */
  cragResult: Annotation<any | null>({
    reducer: (left: any | null, right: any | null) => right,
    default: () => null,
  }),

  /**
   * Phase 2: Retry count for CRAG/Critic loop
   */
  retryCount: Annotation<number>({
    reducer: (left: number, right: number) => left + right,
    default: () => 0,
  }),
  
  /**
   * The final answer generated by the agent.
   */
  finalAnswer: Annotation<string | null>({
    reducer: (left: string | null, right: string | null) => right,
    default: () => null,
  }),
});

export type AgentStateType = typeof AgentState.State;
